---
- name: Launch an Amazon EC2 Instance
  hosts: localhost
  vars_files: ec2_access_creds.yml
  gather_facts: false
  tasks:
    - name: Create and Launch an EC2 Instance
      ec2:
        key_name: "{{ ec2_key_pair}}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_ami }}"
        wait: yes
        assign_public_ip: "{{ ec2_public_ip }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ ec2_region }}"
        vpc_subnet_id: "{{ ec2_vpc_id }}"
        instance_tags:
          Name: "{{ ec2_tag_name }}"
          Purpose: "{{ ec2_tag_purpose }}"